version: '2'
services:
  frontend:
    build: frontend
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - backend
    environment:
      ENDPOINT: http://192.168.99.100:9000/api
  backend:
    build: backend
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "9000:9000"
    environment:
       APPID: HUPS